Bump tested WP to 5.6
sendsmaily/smaily-cf7-plugin pull request #43
Opened 2020-12-01 17:08 UTC by TomAbel

#39 

Will try RC2 as it should be available Dec 1. No issues on RC1

2020-12-10 13:58 UTC, TomAbel commented
Tested it several times. I encountered a wp_die() when updating CF7 via /update-core.php but I cannot replicate it. It popped up the wp_die() in the midst of the down-scrolling update text. Nevertheless the update was performed successfully. Maybe WP forgot to enable maintenence mode in some glitch? No idea.

Found no issues, plugin looks compatible with 5.6.

2020-12-11 15:45 UTC, kaittodesk requested changes
Are you sure you tested it against WordPress 5.6? Development environment's WordPress tag is `5.5-php7.3-apache` :)

If you did, please bump the development environment's WordPress version to 5.6 as well.

2020-12-11 15:49 UTC, TomAbel commented
> Are you sure you tested it against WordPress 5.6? Development environment's WordPress tag is `5.5-php7.3-apache` :)
> 
> If you did, please bump the development environment's WordPress version to 5.6 as well.

Yes, I added these lines to the Dockerfile. The 5.6 docker image was unavailable yesterday. Will add it now
 RUN mkdir /usr/src/wordpress/wp-content/plugins/wordpress-beta-tester \
  && wget https://downloads.wordpress.org/plugin/wordpress-beta-tester.3.0.9.zip \
  && unzip wordpress-beta-tester.3.0.9.zip \
  && mv wordpress-beta-tester/* /usr/src/wordpress/wp-content/plugins/wordpress-beta-tester \
  && rm wordpress-beta-tester.3.0.9.zip

2020-12-11 15:52 UTC, kaittodesk approved these changes

2020-12-11 16:06 UTC, merged